Koka/odbc-rs

README.md, src/lib.rs
On my system (stable-x64-msvc) c_long is an i32. The test code does therefore not compile on my machine. Using SQLLEN should work fine on all platforms.
=> SQLLEN for buffer length

.travis.yml, src/environment.rs, src/lib.rs, travis/odbc.ini
added three methods to `Environment`: `system_data_sources`, `user_data_sources` and `data_sources` which list system, user or all data sources. To avoid code repetition, some of the code of `Environment::drivers` has been moved into helper methods. Looking forward to your feedback!
=> List odbc datasources

src/data_source.rs, src/diagnostics.rs, src/environment.rs, src/error.rs, src/lib.rs, src/odbc_object.rs, src/raii.rs, src/safe/environment.rs, src/safe/mod.rs, src/statement.rs
* Results of `SQLFreeHandle` is now always evaluated.
* This showed that two test cases were in fact broken. Added `disconnect` method to `data_source` in order to fix them
=> Introduce generic Raii struct to handle allocation and deallocation of handles

README.md, examples/connect.rs, src/statement.rs
Introduces `Cursor` for iteration over result sets. This prevents users from calling `get_data` before the first call to `SQLFetch`, or after it returned `SQL_NO_DATA`.
=> State machine 2

Cargo.toml, examples/connect.rs, src/environment/list_data_sources.rs, src/environment/mod.rs, src/ffi.rs, src/result.rs, src/statement/bind_parameter.rs, src/statement/input.rs, src/statement/mod.rs, src/statement/output.rs, src/statement/types.rs, tests/input_parameter.rs, tests/libs.rs, tests/native_types.rs
* adds `Statement::bind_parameter`
* an additional lifetime parameter has been added to `Statement` to ensure it does not outlive its buffers
* changing buffers while they are bound is not possible in safe code
=> Binding of parameters in safe code

src/diagnostics.rs
In some non utf-8 environment(like windows with japanese locale),
panic will be occured when call DiagnosticRecord.fmt() because of encoding error.
So I add the functions for raw message data.
If raw message data can be acquired, it can be decoded with another crate(e.g. rust-encoding).
=> add get raw error data functions for avoiding encoding error

examples/custom_get_data.rs, src/statement/types.rs
Sadly the requirements for unsafe Rust code are much higher than for C Code. Among other things a piece of unsafe Rust code must protect its invariants even in the presence of Bugs in user Code. The OdbcType can not be implemented in safe code since a wrong implementation may lead to invalid memory access. I changed the code example to demonstrate how the user could add support for custom types in safe code without any changes to `odbc-rs`.
=> declared OdbcType trait unsafe

README.md, examples/bind_params.rs, examples/column_descriptions.rs, examples/connect.rs, examples/custom_get_data.rs, examples/print_drivers_and_datasources.rs, src/environment/mod.rs, src/lib.rs, src/result.rs, src/statement/input.rs, src/statement/mod.rs, src/statement/prepare.rs, tests/input_parameter.rs, tests/libs.rs, tests/native_types.rs
There no longer is a NoVersion state of the environment. While this will prevent some exotic use cases it is the right thing to do for almost every application. User who need more control could use `odbc_safe` directly.
=> Simplify Environment states

Cargo.toml, examples/bind_params.rs, examples/column_descriptions.rs, examples/connect.rs, examples/custom_get_data.rs, src/connection.rs, src/data_source.rs, src/environment/mod.rs, src/lib.rs, src/odbc_object.rs, src/raii.rs, src/statement/input.rs, src/statement/mod.rs, src/statement/prepare.rs, tests/input_parameter.rs, tests/libs.rs, tests/native_types.rs
The former `DataSource` now knows only the `Connected` state and has therefore been aptly renamed into `Connection`. The methods to create a `Connection` have been moved into an `Environment` `impl` to be easier to discover. All in all this removed mostly one line of code from each Test or Example and made the type signatures slightly more ergonomic. There is a small price to pay though: Connecting to a Data Source now always implies a new allocation of a Connection Handle. Users who want to avoid this have to drop down to the `odbc_safe` layer.
=> Refactored DataSource into Connection

src/statement/types.rs, tests/input_parameter.rs, tests/native_types.rs
Fixes https://github.com/Koka/odbc-rs/issues/52 (with CString support)
Fixes https://github.com/Koka/odbc-rs/issues/48 (with Vec<u8> and &[u8] support)
=> Support for binary types and non UTF-8 strings

examples/bind_params.rs, src/statement/input.rs, src/statement/mod.rs
This attempts to fix #53 by keeping ind_or_str_len buffer alive for enough time to perform sql statement call.
=> Attempt to fix #53

src/diagnostics.rs
Closes #86
Some drivers pad the message with null-chars (which is still a valid C string, but not a valid Rust string).
That leads to a crash when trying to use the resulting DiagnosticRecord object.
This happened to me when using Oracle 11g.
=> Remove null-char padding from diagnostic messages.

src/diagnostics.rs, src/environment/list_data_sources.rs, src/environment/mod.rs, src/raii.rs, src/result.rs
Some drivers can return no diagnostics data after encountering certain errors. This was resulting in a panic because of the forceful unwrap of `None` values.
=> Fix crash on errors where no diagnostics info is available.

src/statement/types.rs
When asked for `char-8` strings from a wide-string column, most ODBC drivers know to encode the data as UTF-8, either by default or with some configuration changes. But some don't support UTF-8 at all and will convert Unicode strings to simple ASCII-strings, losing data in the process.
This adds the possibility to ask for `char-16` strings, which should provide a workaround to lossless retrieve the data  from wide-strings columns, when UTF-8 support is not present.
=> Add support for retrieving wide strings as UTF-16

src/statement/mod.rs, src/statement/types.rs
I have added some time and date related type implementations for `OdbcType`. This allows to access `SqlDate`, `SqlTime`, `SqlSsTime2` and `SqlTimestamp` via `Cursor::get_data`. I did some tests with SQL Server and MonetDB but this is far from well tested. Also not sure on exporting sys types via alias or should this implement chrono types or similar instead.
=> OdbcType impl for some time and date types

src/statement/input.rs, src/statement/types.rs
I have added impl of `OdbcType` for `Option<T>` where `T` is `OdbcType` and handling case of `null` value in bind parameters. This allows me to bind `None`/`NULL` values in parametrized queries.
=> Parameter binding of Option<T> as possibly NULL value

src/statement/output.rs, src/statement/types.rs
This PR fixes issue with sending only half of the Unicode string and handling of receiving of Unicode strings where two last null bytes need to be removed from intermediate buffers instead of one.
=> fix for incorrect column_size and tailing null handling for Unicode strings

src/statement/types.rs
I found out that sqlite see no difference between different integer types. INTEGER and BIGINT has the same affinity. Therefore I can't write correct test to reproduce bug with sqlite. I saw some tests that reference to PostgresSQL, but I'm not sure I can use it with my tests.
Anyway, for MS SQL mapping i64 and u64 to SQL_EXT_BIGINT works perfectly.
=> OdbcType implementation fix for i64 and u64.

src/statement/mod.rs
As I described in Issue https://github.com/Koka/odbc-rs/issues/110, I have problems with the tables command and MariaDB.
This PR Introduces a new method, pub fn tables_opt_str, which uses optionals.
=> Optional tables

src/statement/mod.rs, src/statement/types.rs
If conversion to `&str` returnes an owned value the current version hits `unimplemented!()` function which panics wihtout any further information. This changes this to a regular `panic!()` and adds an error message which points the user in the right direction. 
Mentioned the panic-case in the docs for the relevant function since mentioning possible panic conditions is a good practice.
=> Improved error message on failed conversion to `&str`

.travis.yml
This drops the build from about 12 minutes (per Rust version) to about 4 minutes (once there's a cache in place), mostly by just avoiding doing extra work! It also fixes the use of global environment variables as they weren't declared correctly.
=> Travis: enable caching and fix global environment variables

src/environment/list_data_sources.rs
This fixes #112. There's some argument about dropping alloc_info entirely in favour of just doing get_info and then retrying with larger buffers as needed if we fail initially, but this at least seems to sort the initial problem. I have no idea why this actually occurs, or why I can't reproduce this outside of Travis, but this does at least work.
=> Fix list_drivers by a non-zero length buffer

examples/custom_get_data.rs, src/raii.rs, src/statement/input.rs, src/statement/mod.rs, src/statement/output.rs, src/statement/prepare.rs, tests/gbk.rs, tests/input_parameter.rs, tests/libs.rs, tests/native_types.rs
Fixes #136.
This is a breaking change.
For an explanation why `;` are needed at the end of a block in the tests see: https://www.reddit.com/r/rust/comments/6dynjz/psa_temporaries_in_final_expression_in_block_live/
Note that I did not get the test to run an pass as I don't have a setup for that. Also, I did not try this with my projects as I am still not migrated to latest `odbc` version.
=> moved PhantomData<'con> to Raii to prevent Raii drop after 'con drop when Statement bound to temporary at final expression in block
